# Generated by Django 5.2 on 2025-04-16 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('statut', models.BooleanField(default=False)),
                ('type_paiement', models.CharField(choices=[('inscription', "Frais d'inscription"), ('scolarite', 'Frais de scolarité')], max_length=50)),
                ('recu_pdf', models.FileField(blank=True, null=True, upload_to='recus/')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anneescolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.eleve')),
            ],
        ),
    ]
