# Generated by Django 5.2 on 2025-04-16 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturations', '0001_initial'),
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='inscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscriptions.inscription'),
        ),
    ]
